//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/tcpapp/GenericAppMsg.msg.
//

#ifndef __INET_GENERICAPPMSG_M_H
#define __INET_GENERICAPPMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class InnerList;
class TwoDInnerList;
class GenericAppMsg;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet


namespace inet {

/**
 * Class generated from <tt>inet/applications/tcpapp/GenericAppMsg.msg:38</tt> by nedtool.
 * <pre>
 * message InnerList
 * {
 *     unsigned int innerArray[];
 * }
 * </pre>
 */
class INET_API InnerList : public ::omnetpp::cMessage
{
  protected:
    unsigned int *innerArray = nullptr;
    size_t innerArray_arraysize = 0;

  private:
    void copy(const InnerList& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InnerList&);

  public:
    InnerList(const char *name=nullptr, short kind=0);
    InnerList(const InnerList& other);
    virtual ~InnerList();
    InnerList& operator=(const InnerList& other);
    virtual InnerList *dup() const override {return new InnerList(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setInnerArrayArraySize(size_t size);
    virtual size_t getInnerArrayArraySize() const;
    virtual unsigned int getInnerArray(size_t k) const;
    virtual void setInnerArray(size_t k, unsigned int innerArray);
    virtual void insertInnerArray(unsigned int innerArray);
    virtual void insertInnerArray(size_t k, unsigned int innerArray);
    virtual void eraseInnerArray(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const InnerList& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, InnerList& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/applications/tcpapp/GenericAppMsg.msg:42</tt> by nedtool.
 * <pre>
 * message TwoDInnerList
 * {
 *     InnerList innerArray[];
 * }
 * </pre>
 */
class INET_API TwoDInnerList : public ::omnetpp::cMessage
{
  protected:
    InnerList *innerArray = nullptr;
    size_t innerArray_arraysize = 0;

  private:
    void copy(const TwoDInnerList& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TwoDInnerList&);

  public:
    TwoDInnerList(const char *name=nullptr, short kind=0);
    TwoDInnerList(const TwoDInnerList& other);
    virtual ~TwoDInnerList();
    TwoDInnerList& operator=(const TwoDInnerList& other);
    virtual TwoDInnerList *dup() const override {return new TwoDInnerList(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setInnerArrayArraySize(size_t size);
    virtual size_t getInnerArrayArraySize() const;
    virtual const InnerList& getInnerArray(size_t k) const;
    virtual InnerList& getInnerArrayForUpdate(size_t k) { return const_cast<InnerList&>(const_cast<TwoDInnerList*>(this)->getInnerArray(k));}
    virtual void setInnerArray(size_t k, const InnerList& innerArray);
    virtual void insertInnerArray(const InnerList& innerArray);
    virtual void insertInnerArray(size_t k, const InnerList& innerArray);
    virtual void eraseInnerArray(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TwoDInnerList& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TwoDInnerList& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/applications/tcpapp/GenericAppMsg.msg:47</tt> by nedtool.
 * <pre>
 * class GenericAppMsg extends FieldsChunk
 * {
 *     B expectedReplyLength;   // in bytes
 *     double replyDelay;       // reply after this many seconds
 *     bool serverClose;        // with TCP: if true, server should close the
 *                              // connection after sending the reply
 *     unsigned long requesterID = 0;
 *     bool is_micro_burst_flow = false;
 *     unsigned long query_id; // only for bursty flows
 *     simtime_t requested_time = 0;
 *     b total_flow_size = b(0);
 *     int responsibility_list[];
 *     int responsibility_gpu_list[];
 *     unsigned long responsibility_flow_id_list[];
 *     //	unsigned int test[unsigned int []]
 *     InnerList ports_to_dest_idx[];
 *     InnerList jump_to_idx[];
 *     // there is a mapping between dst_idx_list and flow_ids_list
 *     // dst_idx_list[i] <---> flow_ids_list[i]
 *     int dst_idx_list[];
 *     unsigned long flow_ids_list[];
 *     string app_name = "";
 *     string app_full_path = "";
 *     int src_gpu_idx = -1;
 *     int dst_gpu_idx = -1;
 * 
 *     // for failure handling
 *     TwoDInnerList all_ports_to_dst[];
 *     TwoDInnerList all_jump_to_idx[];
 *     int current_tree_idx = -1;
 * 
 * 	// for ring allreduce
 *     int ring_end_server_idx = -1;
 *     int ring_end_gpu_idx = -1;
 * 
 *     bool optireduce_in_reduction_phase = false;
 * 
 *     // for binary tree allreduce/allgather
 *     int tree_search_type = -1;
 *     int tree_traversal_dir = -1;
 * 
 *     int collective_type = -1;
 *     int collective_alg_type = -1;
 * 
 *     // ina
 *     int ina_leaf_aggregation_num = -1;
 *     int ina_spine_aggregation_num = -1;
 *     int ina_core_aggregation_num = -1;
 * 
 *     unsigned long seq_num = 0; // seq num starts from 1
 *     unsigned int collective_scale = 0;
 * 
 *     // rsbf
 *     unsigned int rsbf_seed_list[];
 *     string rsbf_bitstream_list[];
 *     unsigned long rsbf_removed_bytes = 0;
 * 
 *     int init_tree_pkt_idx = -1;
 * 
 *     int dst_tor_idx = -1;
 * 
 *     unsigned long partial_mcast_original_flow_size_bytes = 0;
 *     simtime_t controller_setup_finish_time = 0;
 * 
 *     int num_msgs_in_tor_group = -1;
 *     int tor_group_idx = -1;
 * 
 *     // CIDR
 *     string agg_cidr_group_id = "";
 *     unsigned long agg_cidr_group_member_count = 0;
 *     string core_cidr_group_id = "";
 *     unsigned long core_cidr_group_member_count = 0;
 * 
 *     bool in_src_sharding = false;	// partial mcast chunk data
 * 
 *     bool using_orca = false;
 * 
 *     bool using_elmo = false;
 *     int useful_data_bytes = 0;	// only used for specific techniques such as elmo!
 *     int elmo_overhead_pop_bytes = 0;	// how much to pop from overhead per multicast tree layer!
 * 
 * }
 * </pre>
 */
class INET_API GenericAppMsg : public ::inet::FieldsChunk
{
  protected:
    B expectedReplyLength = B(-1);
    double replyDelay = 0;
    bool serverClose = false;
    unsigned long requesterID = 0;
    bool is_micro_burst_flow = false;
    unsigned long query_id = 0;
    omnetpp::simtime_t requested_time = 0;
    b total_flow_size = b(0);
    int *responsibility_list = nullptr;
    size_t responsibility_list_arraysize = 0;
    int *responsibility_gpu_list = nullptr;
    size_t responsibility_gpu_list_arraysize = 0;
    unsigned long *responsibility_flow_id_list = nullptr;
    size_t responsibility_flow_id_list_arraysize = 0;
    InnerList *ports_to_dest_idx = nullptr;
    size_t ports_to_dest_idx_arraysize = 0;
    InnerList *jump_to_idx = nullptr;
    size_t jump_to_idx_arraysize = 0;
    int *dst_idx_list = nullptr;
    size_t dst_idx_list_arraysize = 0;
    unsigned long *flow_ids_list = nullptr;
    size_t flow_ids_list_arraysize = 0;
    omnetpp::opp_string app_name = "";
    omnetpp::opp_string app_full_path = "";
    int src_gpu_idx = -1;
    int dst_gpu_idx = -1;
    TwoDInnerList *all_ports_to_dst = nullptr;
    size_t all_ports_to_dst_arraysize = 0;
    TwoDInnerList *all_jump_to_idx = nullptr;
    size_t all_jump_to_idx_arraysize = 0;
    int current_tree_idx = -1;
    int ring_end_server_idx = -1;
    int ring_end_gpu_idx = -1;
    bool optireduce_in_reduction_phase = false;
    int tree_search_type = -1;
    int tree_traversal_dir = -1;
    int collective_type = -1;
    int collective_alg_type = -1;
    int ina_leaf_aggregation_num = -1;
    int ina_spine_aggregation_num = -1;
    int ina_core_aggregation_num = -1;
    unsigned long seq_num = 0;
    unsigned int collective_scale = 0;
    unsigned int *rsbf_seed_list = nullptr;
    size_t rsbf_seed_list_arraysize = 0;
    omnetpp::opp_string *rsbf_bitstream_list = nullptr;
    size_t rsbf_bitstream_list_arraysize = 0;
    unsigned long rsbf_removed_bytes = 0;
    int init_tree_pkt_idx = -1;
    int dst_tor_idx = -1;
    unsigned long partial_mcast_original_flow_size_bytes = 0;
    omnetpp::simtime_t controller_setup_finish_time = 0;
    int num_msgs_in_tor_group = -1;
    int tor_group_idx = -1;
    omnetpp::opp_string agg_cidr_group_id = "";
    unsigned long agg_cidr_group_member_count = 0;
    omnetpp::opp_string core_cidr_group_id = "";
    unsigned long core_cidr_group_member_count = 0;
    bool in_src_sharding = false;
    bool using_orca = false;
    bool using_elmo = false;
    int useful_data_bytes = 0;
    int elmo_overhead_pop_bytes = 0;

  private:
    void copy(const GenericAppMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GenericAppMsg&);

  public:
    GenericAppMsg();
    GenericAppMsg(const GenericAppMsg& other);
    virtual ~GenericAppMsg();
    GenericAppMsg& operator=(const GenericAppMsg& other);
    virtual GenericAppMsg *dup() const override {return new GenericAppMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual B getExpectedReplyLength() const;
    virtual void setExpectedReplyLength(B expectedReplyLength);
    virtual double getReplyDelay() const;
    virtual void setReplyDelay(double replyDelay);
    virtual bool getServerClose() const;
    virtual void setServerClose(bool serverClose);
    virtual unsigned long getRequesterID() const;
    virtual void setRequesterID(unsigned long requesterID);
    virtual bool getIs_micro_burst_flow() const;
    virtual void setIs_micro_burst_flow(bool is_micro_burst_flow);
    virtual unsigned long getQuery_id() const;
    virtual void setQuery_id(unsigned long query_id);
    virtual omnetpp::simtime_t getRequested_time() const;
    virtual void setRequested_time(omnetpp::simtime_t requested_time);
    virtual b getTotal_flow_size() const;
    virtual void setTotal_flow_size(b total_flow_size);
    virtual void setResponsibility_listArraySize(size_t size);
    virtual size_t getResponsibility_listArraySize() const;
    virtual int getResponsibility_list(size_t k) const;
    virtual void setResponsibility_list(size_t k, int responsibility_list);
    virtual void insertResponsibility_list(int responsibility_list);
    virtual void insertResponsibility_list(size_t k, int responsibility_list);
    virtual void eraseResponsibility_list(size_t k);
    virtual void setResponsibility_gpu_listArraySize(size_t size);
    virtual size_t getResponsibility_gpu_listArraySize() const;
    virtual int getResponsibility_gpu_list(size_t k) const;
    virtual void setResponsibility_gpu_list(size_t k, int responsibility_gpu_list);
    virtual void insertResponsibility_gpu_list(int responsibility_gpu_list);
    virtual void insertResponsibility_gpu_list(size_t k, int responsibility_gpu_list);
    virtual void eraseResponsibility_gpu_list(size_t k);
    virtual void setResponsibility_flow_id_listArraySize(size_t size);
    virtual size_t getResponsibility_flow_id_listArraySize() const;
    virtual unsigned long getResponsibility_flow_id_list(size_t k) const;
    virtual void setResponsibility_flow_id_list(size_t k, unsigned long responsibility_flow_id_list);
    virtual void insertResponsibility_flow_id_list(unsigned long responsibility_flow_id_list);
    virtual void insertResponsibility_flow_id_list(size_t k, unsigned long responsibility_flow_id_list);
    virtual void eraseResponsibility_flow_id_list(size_t k);
    virtual void setPorts_to_dest_idxArraySize(size_t size);
    virtual size_t getPorts_to_dest_idxArraySize() const;
    virtual const InnerList& getPorts_to_dest_idx(size_t k) const;
    virtual InnerList& getPorts_to_dest_idxForUpdate(size_t k) { handleChange();return const_cast<InnerList&>(const_cast<GenericAppMsg*>(this)->getPorts_to_dest_idx(k));}
    virtual void setPorts_to_dest_idx(size_t k, const InnerList& ports_to_dest_idx);
    virtual void insertPorts_to_dest_idx(const InnerList& ports_to_dest_idx);
    virtual void insertPorts_to_dest_idx(size_t k, const InnerList& ports_to_dest_idx);
    virtual void erasePorts_to_dest_idx(size_t k);
    virtual void setJump_to_idxArraySize(size_t size);
    virtual size_t getJump_to_idxArraySize() const;
    virtual const InnerList& getJump_to_idx(size_t k) const;
    virtual InnerList& getJump_to_idxForUpdate(size_t k) { handleChange();return const_cast<InnerList&>(const_cast<GenericAppMsg*>(this)->getJump_to_idx(k));}
    virtual void setJump_to_idx(size_t k, const InnerList& jump_to_idx);
    virtual void insertJump_to_idx(const InnerList& jump_to_idx);
    virtual void insertJump_to_idx(size_t k, const InnerList& jump_to_idx);
    virtual void eraseJump_to_idx(size_t k);
    virtual void setDst_idx_listArraySize(size_t size);
    virtual size_t getDst_idx_listArraySize() const;
    virtual int getDst_idx_list(size_t k) const;
    virtual void setDst_idx_list(size_t k, int dst_idx_list);
    virtual void insertDst_idx_list(int dst_idx_list);
    virtual void insertDst_idx_list(size_t k, int dst_idx_list);
    virtual void eraseDst_idx_list(size_t k);
    virtual void setFlow_ids_listArraySize(size_t size);
    virtual size_t getFlow_ids_listArraySize() const;
    virtual unsigned long getFlow_ids_list(size_t k) const;
    virtual void setFlow_ids_list(size_t k, unsigned long flow_ids_list);
    virtual void insertFlow_ids_list(unsigned long flow_ids_list);
    virtual void insertFlow_ids_list(size_t k, unsigned long flow_ids_list);
    virtual void eraseFlow_ids_list(size_t k);
    virtual const char * getApp_name() const;
    virtual void setApp_name(const char * app_name);
    virtual const char * getApp_full_path() const;
    virtual void setApp_full_path(const char * app_full_path);
    virtual int getSrc_gpu_idx() const;
    virtual void setSrc_gpu_idx(int src_gpu_idx);
    virtual int getDst_gpu_idx() const;
    virtual void setDst_gpu_idx(int dst_gpu_idx);
    virtual void setAll_ports_to_dstArraySize(size_t size);
    virtual size_t getAll_ports_to_dstArraySize() const;
    virtual const TwoDInnerList& getAll_ports_to_dst(size_t k) const;
    virtual TwoDInnerList& getAll_ports_to_dstForUpdate(size_t k) { handleChange();return const_cast<TwoDInnerList&>(const_cast<GenericAppMsg*>(this)->getAll_ports_to_dst(k));}
    virtual void setAll_ports_to_dst(size_t k, const TwoDInnerList& all_ports_to_dst);
    virtual void insertAll_ports_to_dst(const TwoDInnerList& all_ports_to_dst);
    virtual void insertAll_ports_to_dst(size_t k, const TwoDInnerList& all_ports_to_dst);
    virtual void eraseAll_ports_to_dst(size_t k);
    virtual void setAll_jump_to_idxArraySize(size_t size);
    virtual size_t getAll_jump_to_idxArraySize() const;
    virtual const TwoDInnerList& getAll_jump_to_idx(size_t k) const;
    virtual TwoDInnerList& getAll_jump_to_idxForUpdate(size_t k) { handleChange();return const_cast<TwoDInnerList&>(const_cast<GenericAppMsg*>(this)->getAll_jump_to_idx(k));}
    virtual void setAll_jump_to_idx(size_t k, const TwoDInnerList& all_jump_to_idx);
    virtual void insertAll_jump_to_idx(const TwoDInnerList& all_jump_to_idx);
    virtual void insertAll_jump_to_idx(size_t k, const TwoDInnerList& all_jump_to_idx);
    virtual void eraseAll_jump_to_idx(size_t k);
    virtual int getCurrent_tree_idx() const;
    virtual void setCurrent_tree_idx(int current_tree_idx);
    virtual int getRing_end_server_idx() const;
    virtual void setRing_end_server_idx(int ring_end_server_idx);
    virtual int getRing_end_gpu_idx() const;
    virtual void setRing_end_gpu_idx(int ring_end_gpu_idx);
    virtual bool getOptireduce_in_reduction_phase() const;
    virtual void setOptireduce_in_reduction_phase(bool optireduce_in_reduction_phase);
    virtual int getTree_search_type() const;
    virtual void setTree_search_type(int tree_search_type);
    virtual int getTree_traversal_dir() const;
    virtual void setTree_traversal_dir(int tree_traversal_dir);
    virtual int getCollective_type() const;
    virtual void setCollective_type(int collective_type);
    virtual int getCollective_alg_type() const;
    virtual void setCollective_alg_type(int collective_alg_type);
    virtual int getIna_leaf_aggregation_num() const;
    virtual void setIna_leaf_aggregation_num(int ina_leaf_aggregation_num);
    virtual int getIna_spine_aggregation_num() const;
    virtual void setIna_spine_aggregation_num(int ina_spine_aggregation_num);
    virtual int getIna_core_aggregation_num() const;
    virtual void setIna_core_aggregation_num(int ina_core_aggregation_num);
    virtual unsigned long getSeq_num() const;
    virtual void setSeq_num(unsigned long seq_num);
    virtual unsigned int getCollective_scale() const;
    virtual void setCollective_scale(unsigned int collective_scale);
    virtual void setRsbf_seed_listArraySize(size_t size);
    virtual size_t getRsbf_seed_listArraySize() const;
    virtual unsigned int getRsbf_seed_list(size_t k) const;
    virtual void setRsbf_seed_list(size_t k, unsigned int rsbf_seed_list);
    virtual void insertRsbf_seed_list(unsigned int rsbf_seed_list);
    virtual void insertRsbf_seed_list(size_t k, unsigned int rsbf_seed_list);
    virtual void eraseRsbf_seed_list(size_t k);
    virtual void setRsbf_bitstream_listArraySize(size_t size);
    virtual size_t getRsbf_bitstream_listArraySize() const;
    virtual const char * getRsbf_bitstream_list(size_t k) const;
    virtual void setRsbf_bitstream_list(size_t k, const char * rsbf_bitstream_list);
    virtual void insertRsbf_bitstream_list(const char * rsbf_bitstream_list);
    virtual void insertRsbf_bitstream_list(size_t k, const char * rsbf_bitstream_list);
    virtual void eraseRsbf_bitstream_list(size_t k);
    virtual unsigned long getRsbf_removed_bytes() const;
    virtual void setRsbf_removed_bytes(unsigned long rsbf_removed_bytes);
    virtual int getInit_tree_pkt_idx() const;
    virtual void setInit_tree_pkt_idx(int init_tree_pkt_idx);
    virtual int getDst_tor_idx() const;
    virtual void setDst_tor_idx(int dst_tor_idx);
    virtual unsigned long getPartial_mcast_original_flow_size_bytes() const;
    virtual void setPartial_mcast_original_flow_size_bytes(unsigned long partial_mcast_original_flow_size_bytes);
    virtual omnetpp::simtime_t getController_setup_finish_time() const;
    virtual void setController_setup_finish_time(omnetpp::simtime_t controller_setup_finish_time);
    virtual int getNum_msgs_in_tor_group() const;
    virtual void setNum_msgs_in_tor_group(int num_msgs_in_tor_group);
    virtual int getTor_group_idx() const;
    virtual void setTor_group_idx(int tor_group_idx);
    virtual const char * getAgg_cidr_group_id() const;
    virtual void setAgg_cidr_group_id(const char * agg_cidr_group_id);
    virtual unsigned long getAgg_cidr_group_member_count() const;
    virtual void setAgg_cidr_group_member_count(unsigned long agg_cidr_group_member_count);
    virtual const char * getCore_cidr_group_id() const;
    virtual void setCore_cidr_group_id(const char * core_cidr_group_id);
    virtual unsigned long getCore_cidr_group_member_count() const;
    virtual void setCore_cidr_group_member_count(unsigned long core_cidr_group_member_count);
    virtual bool getIn_src_sharding() const;
    virtual void setIn_src_sharding(bool in_src_sharding);
    virtual bool getUsing_orca() const;
    virtual void setUsing_orca(bool using_orca);
    virtual bool getUsing_elmo() const;
    virtual void setUsing_elmo(bool using_elmo);
    virtual int getUseful_data_bytes() const;
    virtual void setUseful_data_bytes(int useful_data_bytes);
    virtual int getElmo_overhead_pop_bytes() const;
    virtual void setElmo_overhead_pop_bytes(int elmo_overhead_pop_bytes);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GenericAppMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GenericAppMsg& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_GENERICAPPMSG_M_H

