//
// Generated file, do not edit! Created by nedtool 5.6 from inet/linklayer/ethernet/EtherFrame.msg.
//

#ifndef __INET_ETHERFRAME_M_H
#define __INET_ETHERFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class EthernetMacHeader;
class EthernetControlFrame;
class EthernetPauseFrame;
class EthernetPadding;
class EthernetFcs;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/packet/Packet_m.h" // import inet.common.packet.Packet

#include "inet/linklayer/common/EtherType_m.h" // import inet.linklayer.common.EtherType

#include "inet/linklayer/common/FcsMode_m.h" // import inet.linklayer.common.FcsMode

#include "inet/linklayer/common/Ieee802Ctrl_m.h" // import inet.linklayer.common.Ieee802Ctrl

#include "inet/linklayer/common/MacAddress_m.h" // import inet.linklayer.common.MacAddress

#include "inet/linklayer/ieee8021q/Ieee8021qHeader_m.h" // import inet.linklayer.ieee8021q.Ieee8021qHeader

#include "inet/applications/tcpapp/GenericAppMsg_m.h" // import inet.applications.tcpapp.GenericAppMsg

// cplusplus {{
#include "inet/linklayer/ethernet/Ethernet.h"
// }}


namespace inet {

/**
 * Enum generated from <tt>inet/linklayer/ethernet/EtherFrame.msg:35</tt> by nedtool.
 * <pre>
 * enum EthernetControlOpCode
 * {
 *     ETHERNET_CONTROL_PAUSE = 1;
 * }
 * </pre>
 */
enum EthernetControlOpCode {
    ETHERNET_CONTROL_PAUSE = 1
};

/**
 * Class generated from <tt>inet/linklayer/ethernet/EtherFrame.msg:45</tt> by nedtool.
 * <pre>
 * //
 * // Ethernet MAC header
 * //
 * class EthernetMacHeader extends FieldsChunk
 * {
 *     chunkLength = B(ETHER_MAC_HEADER_BYTES);
 *     MacAddress dest;
 *     MacAddress src;
 *     Ieee8021qHeader *cTag \@owned;
 *     Ieee8021qHeader *sTag \@owned;
 *     int typeOrLength;
 *     int hop_count = 0;
 *     // -1 for prio_queue_id means that we should use default queue
 *     int prio_queue_idx = -1;
 *     // For Vertigo
 *     bool isFB = false;
 *     bool allow_same_input_output = false;
 *     int original_interface_id = -1;
 * 
 *     // For PABO
 *     int bouncedDistance;	// passBackHop
 *     int maxBouncedDistance;		// maxPassBackHop
 *     int bouncedHop;	// passBackNum
 *     int totalHopNum;
 * 
 *     // For further measurements
 *     bool is_bursty = false;
 *     b payload_length = b(0);
 *     b total_length = b(0); // total lenght that the payload is part of
 *     b offset = b(0);
 * 
 *     // For V2
 *     bool is_v2_dropped_packet_header = false;
 *     uint16_t queue_occupancy = -1;
 * 
 *     // swift
 *     simtime_t time_packet_received_at_nic;  // this is added to every packet when it lands in a host
 *     simtime_t local_nic_rx_delay; // this is the time packet quits the nic rcv queue to move up to other layers
 *     simtime_t remote_queueing_time;  // This is the time ack packet is sent - the time data packet is received at host
 * 
 * 
 *     // fabric_delay
 *     simtime_t fabric_delay_time_sent_from_source;
 * 
 *     // bolt
 *     simtime_t time_packet_sent_from_src;
 *     bool is_deflected = false;
 * 
 *     // network assisted routing
 *     InnerList ports_to_dest_idx[];
 *     InnerList jump_to_idx[];
 *     int dst_idx_list[];
 *     unsigned int start_from_idx;
 * 
 *     // for failure handling
 *     TwoDInnerList all_ports_to_dst[];
 *     TwoDInnerList all_jump_to_idx[];
 *     int current_tree_idx = -1;
 * 
 *     // ina
 *     int ina_leaf_aggregation_num = -1;
 *     int ina_spine_aggregation_num = -1;
 *     int ina_core_aggregation_num = -1;
 * 
 *     int tree_direction = -1;
 *     unsigned long query_id = 0;
 *     unsigned long flow_id = 0;
 *     unsigned int collective_scale = 0;
 * 
 *     int collective_alg = -1;
 * 
 *     // pfc
 *     int pfc_signal = -1;
 * 
 *     // ecn_mark
 *     bool is_ecn_marked = false;
 * 
 *     // dcqcn cnp
 *     unsigned long cnp_flow_id;
 *     int cnp_src_gpu_id;
 * 
 *     int src_gpu_idx = -1;
 * 
 *     unsigned long seq_num = 0;
 * 
 *     bool orca_pkt_seen_agent = false;
 *     int orca_agent_port_index = -1;
 * 
 *     // rsbf
 *     unsigned int rsbf_seed_list[];
 *     string rsbf_bitstream_list[];
 *     bool rsbf_redundant_send = false;
 * 
 *     int dst_tor_idx = -1;
 * 
 *     Packet *partial_mcast_core_pkt[];
 *     bool multicast_pkt_in_programmable_core = false;
 * 
 *     // CIDR
 *     string agg_cidr_group_id = "";
 *     unsigned long agg_cidr_group_member_count = 0;
 *     bool is_redundant_cidr_pkt = false;
 *     Packet *CIDR_agg_pkt[];
 *     bool multicast_pkt_in_CIDR_agg = false;
 * 
 *     string core_cidr_group_id = "";
 *     unsigned long core_cidr_group_member_count = 0;
 *     Packet *CIDR_core_pkt[];
 *     bool multicast_pkt_in_CIDR_core = false;
 * 
 *     // drop recovery (notif/deflect on drop)
 *     Packet *original_pkt = nullptr;
 *     bool is_drop_notif = false;
 *     unsigned int input_ports_passed[];
 *     string original_pkt_name = "";
 *     simtime_t recovery_time = 0; // only used by ace to know when it can use a tree again!
 * 
 *     // failure and recovery
 *     MacAddress affected_addresses[];
 * 
 *     // swift send times
 *     simtime_t swift_send_time = 0;
 *     long cidr_base_flow_id = -1;	// this is the flow id that is carried by the first packet when doing cidr
 *     int cidr_base_src_gpu_idx = -1;	// this is the flow id that is carried by the first packet when doing cidr
 * 
 *     bool in_src_sharding = false;	// partial mcast chunk data
 * 
 *     bool using_orca = false;
 * 
 *     bool using_elmo = false;
 * 
 * }
 * </pre>
 */
class INET_API EthernetMacHeader : public ::inet::FieldsChunk
{
  protected:
    MacAddress dest;
    MacAddress src;
    Ieee8021qHeader * cTag = nullptr;
    Ieee8021qHeader * sTag = nullptr;
    int typeOrLength = 0;
    int hop_count = 0;
    int prio_queue_idx = -1;
    bool isFB_ = false;
    bool allow_same_input_output = false;
    int original_interface_id = -1;
    int bouncedDistance = 0;
    int maxBouncedDistance = 0;
    int bouncedHop = 0;
    int totalHopNum = 0;
    bool is_bursty = false;
    b payload_length = b(0);
    b total_length = b(0);
    b offset = b(0);
    bool is_v2_dropped_packet_header = false;
    uint16_t queue_occupancy = -1;
    omnetpp::simtime_t time_packet_received_at_nic = SIMTIME_ZERO;
    omnetpp::simtime_t local_nic_rx_delay = SIMTIME_ZERO;
    omnetpp::simtime_t remote_queueing_time = SIMTIME_ZERO;
    omnetpp::simtime_t fabric_delay_time_sent_from_source = SIMTIME_ZERO;
    omnetpp::simtime_t time_packet_sent_from_src = SIMTIME_ZERO;
    bool is_deflected = false;
    InnerList *ports_to_dest_idx = nullptr;
    size_t ports_to_dest_idx_arraysize = 0;
    InnerList *jump_to_idx = nullptr;
    size_t jump_to_idx_arraysize = 0;
    int *dst_idx_list = nullptr;
    size_t dst_idx_list_arraysize = 0;
    unsigned int start_from_idx = 0;
    TwoDInnerList *all_ports_to_dst = nullptr;
    size_t all_ports_to_dst_arraysize = 0;
    TwoDInnerList *all_jump_to_idx = nullptr;
    size_t all_jump_to_idx_arraysize = 0;
    int current_tree_idx = -1;
    int ina_leaf_aggregation_num = -1;
    int ina_spine_aggregation_num = -1;
    int ina_core_aggregation_num = -1;
    int tree_direction = -1;
    unsigned long query_id = 0;
    unsigned long flow_id = 0;
    unsigned int collective_scale = 0;
    int collective_alg = -1;
    int pfc_signal = -1;
    bool is_ecn_marked = false;
    unsigned long cnp_flow_id = 0;
    int cnp_src_gpu_id = 0;
    int src_gpu_idx = -1;
    unsigned long seq_num = 0;
    bool orca_pkt_seen_agent = false;
    int orca_agent_port_index = -1;
    unsigned int *rsbf_seed_list = nullptr;
    size_t rsbf_seed_list_arraysize = 0;
    omnetpp::opp_string *rsbf_bitstream_list = nullptr;
    size_t rsbf_bitstream_list_arraysize = 0;
    bool rsbf_redundant_send = false;
    int dst_tor_idx = -1;
    Packet * *partial_mcast_core_pkt = nullptr;
    size_t partial_mcast_core_pkt_arraysize = 0;
    bool multicast_pkt_in_programmable_core = false;
    omnetpp::opp_string agg_cidr_group_id = "";
    unsigned long agg_cidr_group_member_count = 0;
    bool is_redundant_cidr_pkt = false;
    Packet * *CIDR_agg_pkt = nullptr;
    size_t CIDR_agg_pkt_arraysize = 0;
    bool multicast_pkt_in_CIDR_agg = false;
    omnetpp::opp_string core_cidr_group_id = "";
    unsigned long core_cidr_group_member_count = 0;
    Packet * *CIDR_core_pkt = nullptr;
    size_t CIDR_core_pkt_arraysize = 0;
    bool multicast_pkt_in_CIDR_core = false;
    Packet * original_pkt = nullptr;
    bool is_drop_notif = false;
    unsigned int *input_ports_passed = nullptr;
    size_t input_ports_passed_arraysize = 0;
    omnetpp::opp_string original_pkt_name = "";
    omnetpp::simtime_t recovery_time = 0;
    MacAddress *affected_addresses = nullptr;
    size_t affected_addresses_arraysize = 0;
    omnetpp::simtime_t swift_send_time = 0;
    long cidr_base_flow_id = -1;
    int cidr_base_src_gpu_idx = -1;
    bool in_src_sharding = false;
    bool using_orca = false;
    bool using_elmo = false;

  private:
    void copy(const EthernetMacHeader& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EthernetMacHeader&);

  public:
    EthernetMacHeader();
    EthernetMacHeader(const EthernetMacHeader& other);
    virtual ~EthernetMacHeader();
    EthernetMacHeader& operator=(const EthernetMacHeader& other);
    virtual EthernetMacHeader *dup() const override {return new EthernetMacHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const MacAddress& getDest() const;
    virtual MacAddress& getDestForUpdate() { handleChange();return const_cast<MacAddress&>(const_cast<EthernetMacHeader*>(this)->getDest());}
    virtual void setDest(const MacAddress& dest);
    virtual const MacAddress& getSrc() const;
    virtual MacAddress& getSrcForUpdate() { handleChange();return const_cast<MacAddress&>(const_cast<EthernetMacHeader*>(this)->getSrc());}
    virtual void setSrc(const MacAddress& src);
    virtual const Ieee8021qHeader * getCTag() const;
    virtual Ieee8021qHeader * getCTagForUpdate() { handleChange();return const_cast<Ieee8021qHeader *>(const_cast<EthernetMacHeader*>(this)->getCTag());}
    virtual Ieee8021qHeader * dropCTag();
    virtual void setCTag(Ieee8021qHeader * cTag);
    virtual const Ieee8021qHeader * getSTag() const;
    virtual Ieee8021qHeader * getSTagForUpdate() { handleChange();return const_cast<Ieee8021qHeader *>(const_cast<EthernetMacHeader*>(this)->getSTag());}
    virtual Ieee8021qHeader * dropSTag();
    virtual void setSTag(Ieee8021qHeader * sTag);
    virtual int getTypeOrLength() const;
    virtual void setTypeOrLength(int typeOrLength);
    virtual int getHop_count() const;
    virtual void setHop_count(int hop_count);
    virtual int getPrio_queue_idx() const;
    virtual void setPrio_queue_idx(int prio_queue_idx);
    virtual bool isFB() const;
    virtual void setIsFB(bool isFB);
    virtual bool getAllow_same_input_output() const;
    virtual void setAllow_same_input_output(bool allow_same_input_output);
    virtual int getOriginal_interface_id() const;
    virtual void setOriginal_interface_id(int original_interface_id);
    virtual int getBouncedDistance() const;
    virtual void setBouncedDistance(int bouncedDistance);
    virtual int getMaxBouncedDistance() const;
    virtual void setMaxBouncedDistance(int maxBouncedDistance);
    virtual int getBouncedHop() const;
    virtual void setBouncedHop(int bouncedHop);
    virtual int getTotalHopNum() const;
    virtual void setTotalHopNum(int totalHopNum);
    virtual bool getIs_bursty() const;
    virtual void setIs_bursty(bool is_bursty);
    virtual b getPayload_length() const;
    virtual void setPayload_length(b payload_length);
    virtual b getTotal_length() const;
    virtual void setTotal_length(b total_length);
    virtual b getOffset() const;
    virtual void setOffset(b offset);
    virtual bool getIs_v2_dropped_packet_header() const;
    virtual void setIs_v2_dropped_packet_header(bool is_v2_dropped_packet_header);
    virtual uint16_t getQueue_occupancy() const;
    virtual void setQueue_occupancy(uint16_t queue_occupancy);
    virtual omnetpp::simtime_t getTime_packet_received_at_nic() const;
    virtual void setTime_packet_received_at_nic(omnetpp::simtime_t time_packet_received_at_nic);
    virtual omnetpp::simtime_t getLocal_nic_rx_delay() const;
    virtual void setLocal_nic_rx_delay(omnetpp::simtime_t local_nic_rx_delay);
    virtual omnetpp::simtime_t getRemote_queueing_time() const;
    virtual void setRemote_queueing_time(omnetpp::simtime_t remote_queueing_time);
    virtual omnetpp::simtime_t getFabric_delay_time_sent_from_source() const;
    virtual void setFabric_delay_time_sent_from_source(omnetpp::simtime_t fabric_delay_time_sent_from_source);
    virtual omnetpp::simtime_t getTime_packet_sent_from_src() const;
    virtual void setTime_packet_sent_from_src(omnetpp::simtime_t time_packet_sent_from_src);
    virtual bool getIs_deflected() const;
    virtual void setIs_deflected(bool is_deflected);
    virtual void setPorts_to_dest_idxArraySize(size_t size);
    virtual size_t getPorts_to_dest_idxArraySize() const;
    virtual const InnerList& getPorts_to_dest_idx(size_t k) const;
    virtual InnerList& getPorts_to_dest_idxForUpdate(size_t k) { handleChange();return const_cast<InnerList&>(const_cast<EthernetMacHeader*>(this)->getPorts_to_dest_idx(k));}
    virtual void setPorts_to_dest_idx(size_t k, const InnerList& ports_to_dest_idx);
    virtual void insertPorts_to_dest_idx(const InnerList& ports_to_dest_idx);
    virtual void insertPorts_to_dest_idx(size_t k, const InnerList& ports_to_dest_idx);
    virtual void erasePorts_to_dest_idx(size_t k);
    virtual void setJump_to_idxArraySize(size_t size);
    virtual size_t getJump_to_idxArraySize() const;
    virtual const InnerList& getJump_to_idx(size_t k) const;
    virtual InnerList& getJump_to_idxForUpdate(size_t k) { handleChange();return const_cast<InnerList&>(const_cast<EthernetMacHeader*>(this)->getJump_to_idx(k));}
    virtual void setJump_to_idx(size_t k, const InnerList& jump_to_idx);
    virtual void insertJump_to_idx(const InnerList& jump_to_idx);
    virtual void insertJump_to_idx(size_t k, const InnerList& jump_to_idx);
    virtual void eraseJump_to_idx(size_t k);
    virtual void setDst_idx_listArraySize(size_t size);
    virtual size_t getDst_idx_listArraySize() const;
    virtual int getDst_idx_list(size_t k) const;
    virtual void setDst_idx_list(size_t k, int dst_idx_list);
    virtual void insertDst_idx_list(int dst_idx_list);
    virtual void insertDst_idx_list(size_t k, int dst_idx_list);
    virtual void eraseDst_idx_list(size_t k);
    virtual unsigned int getStart_from_idx() const;
    virtual void setStart_from_idx(unsigned int start_from_idx);
    virtual void setAll_ports_to_dstArraySize(size_t size);
    virtual size_t getAll_ports_to_dstArraySize() const;
    virtual const TwoDInnerList& getAll_ports_to_dst(size_t k) const;
    virtual TwoDInnerList& getAll_ports_to_dstForUpdate(size_t k) { handleChange();return const_cast<TwoDInnerList&>(const_cast<EthernetMacHeader*>(this)->getAll_ports_to_dst(k));}
    virtual void setAll_ports_to_dst(size_t k, const TwoDInnerList& all_ports_to_dst);
    virtual void insertAll_ports_to_dst(const TwoDInnerList& all_ports_to_dst);
    virtual void insertAll_ports_to_dst(size_t k, const TwoDInnerList& all_ports_to_dst);
    virtual void eraseAll_ports_to_dst(size_t k);
    virtual void setAll_jump_to_idxArraySize(size_t size);
    virtual size_t getAll_jump_to_idxArraySize() const;
    virtual const TwoDInnerList& getAll_jump_to_idx(size_t k) const;
    virtual TwoDInnerList& getAll_jump_to_idxForUpdate(size_t k) { handleChange();return const_cast<TwoDInnerList&>(const_cast<EthernetMacHeader*>(this)->getAll_jump_to_idx(k));}
    virtual void setAll_jump_to_idx(size_t k, const TwoDInnerList& all_jump_to_idx);
    virtual void insertAll_jump_to_idx(const TwoDInnerList& all_jump_to_idx);
    virtual void insertAll_jump_to_idx(size_t k, const TwoDInnerList& all_jump_to_idx);
    virtual void eraseAll_jump_to_idx(size_t k);
    virtual int getCurrent_tree_idx() const;
    virtual void setCurrent_tree_idx(int current_tree_idx);
    virtual int getIna_leaf_aggregation_num() const;
    virtual void setIna_leaf_aggregation_num(int ina_leaf_aggregation_num);
    virtual int getIna_spine_aggregation_num() const;
    virtual void setIna_spine_aggregation_num(int ina_spine_aggregation_num);
    virtual int getIna_core_aggregation_num() const;
    virtual void setIna_core_aggregation_num(int ina_core_aggregation_num);
    virtual int getTree_direction() const;
    virtual void setTree_direction(int tree_direction);
    virtual unsigned long getQuery_id() const;
    virtual void setQuery_id(unsigned long query_id);
    virtual unsigned long getFlow_id() const;
    virtual void setFlow_id(unsigned long flow_id);
    virtual unsigned int getCollective_scale() const;
    virtual void setCollective_scale(unsigned int collective_scale);
    virtual int getCollective_alg() const;
    virtual void setCollective_alg(int collective_alg);
    virtual int getPfc_signal() const;
    virtual void setPfc_signal(int pfc_signal);
    virtual bool getIs_ecn_marked() const;
    virtual void setIs_ecn_marked(bool is_ecn_marked);
    virtual unsigned long getCnp_flow_id() const;
    virtual void setCnp_flow_id(unsigned long cnp_flow_id);
    virtual int getCnp_src_gpu_id() const;
    virtual void setCnp_src_gpu_id(int cnp_src_gpu_id);
    virtual int getSrc_gpu_idx() const;
    virtual void setSrc_gpu_idx(int src_gpu_idx);
    virtual unsigned long getSeq_num() const;
    virtual void setSeq_num(unsigned long seq_num);
    virtual bool getOrca_pkt_seen_agent() const;
    virtual void setOrca_pkt_seen_agent(bool orca_pkt_seen_agent);
    virtual int getOrca_agent_port_index() const;
    virtual void setOrca_agent_port_index(int orca_agent_port_index);
    virtual void setRsbf_seed_listArraySize(size_t size);
    virtual size_t getRsbf_seed_listArraySize() const;
    virtual unsigned int getRsbf_seed_list(size_t k) const;
    virtual void setRsbf_seed_list(size_t k, unsigned int rsbf_seed_list);
    virtual void insertRsbf_seed_list(unsigned int rsbf_seed_list);
    virtual void insertRsbf_seed_list(size_t k, unsigned int rsbf_seed_list);
    virtual void eraseRsbf_seed_list(size_t k);
    virtual void setRsbf_bitstream_listArraySize(size_t size);
    virtual size_t getRsbf_bitstream_listArraySize() const;
    virtual const char * getRsbf_bitstream_list(size_t k) const;
    virtual void setRsbf_bitstream_list(size_t k, const char * rsbf_bitstream_list);
    virtual void insertRsbf_bitstream_list(const char * rsbf_bitstream_list);
    virtual void insertRsbf_bitstream_list(size_t k, const char * rsbf_bitstream_list);
    virtual void eraseRsbf_bitstream_list(size_t k);
    virtual bool getRsbf_redundant_send() const;
    virtual void setRsbf_redundant_send(bool rsbf_redundant_send);
    virtual int getDst_tor_idx() const;
    virtual void setDst_tor_idx(int dst_tor_idx);
    virtual void setPartial_mcast_core_pktArraySize(size_t size);
    virtual size_t getPartial_mcast_core_pktArraySize() const;
    virtual const Packet * getPartial_mcast_core_pkt(size_t k) const;
    virtual Packet * getPartial_mcast_core_pktForUpdate(size_t k) { handleChange();return const_cast<Packet *>(const_cast<EthernetMacHeader*>(this)->getPartial_mcast_core_pkt(k));}
    virtual void setPartial_mcast_core_pkt(size_t k, Packet * partial_mcast_core_pkt);
    virtual void insertPartial_mcast_core_pkt(Packet * partial_mcast_core_pkt);
    virtual void insertPartial_mcast_core_pkt(size_t k, Packet * partial_mcast_core_pkt);
    virtual void erasePartial_mcast_core_pkt(size_t k);
    virtual bool getMulticast_pkt_in_programmable_core() const;
    virtual void setMulticast_pkt_in_programmable_core(bool multicast_pkt_in_programmable_core);
    virtual const char * getAgg_cidr_group_id() const;
    virtual void setAgg_cidr_group_id(const char * agg_cidr_group_id);
    virtual unsigned long getAgg_cidr_group_member_count() const;
    virtual void setAgg_cidr_group_member_count(unsigned long agg_cidr_group_member_count);
    virtual bool getIs_redundant_cidr_pkt() const;
    virtual void setIs_redundant_cidr_pkt(bool is_redundant_cidr_pkt);
    virtual void setCIDR_agg_pktArraySize(size_t size);
    virtual size_t getCIDR_agg_pktArraySize() const;
    virtual const Packet * getCIDR_agg_pkt(size_t k) const;
    virtual Packet * getCIDR_agg_pktForUpdate(size_t k) { handleChange();return const_cast<Packet *>(const_cast<EthernetMacHeader*>(this)->getCIDR_agg_pkt(k));}
    virtual void setCIDR_agg_pkt(size_t k, Packet * CIDR_agg_pkt);
    virtual void insertCIDR_agg_pkt(Packet * CIDR_agg_pkt);
    virtual void insertCIDR_agg_pkt(size_t k, Packet * CIDR_agg_pkt);
    virtual void eraseCIDR_agg_pkt(size_t k);
    virtual bool getMulticast_pkt_in_CIDR_agg() const;
    virtual void setMulticast_pkt_in_CIDR_agg(bool multicast_pkt_in_CIDR_agg);
    virtual const char * getCore_cidr_group_id() const;
    virtual void setCore_cidr_group_id(const char * core_cidr_group_id);
    virtual unsigned long getCore_cidr_group_member_count() const;
    virtual void setCore_cidr_group_member_count(unsigned long core_cidr_group_member_count);
    virtual void setCIDR_core_pktArraySize(size_t size);
    virtual size_t getCIDR_core_pktArraySize() const;
    virtual const Packet * getCIDR_core_pkt(size_t k) const;
    virtual Packet * getCIDR_core_pktForUpdate(size_t k) { handleChange();return const_cast<Packet *>(const_cast<EthernetMacHeader*>(this)->getCIDR_core_pkt(k));}
    virtual void setCIDR_core_pkt(size_t k, Packet * CIDR_core_pkt);
    virtual void insertCIDR_core_pkt(Packet * CIDR_core_pkt);
    virtual void insertCIDR_core_pkt(size_t k, Packet * CIDR_core_pkt);
    virtual void eraseCIDR_core_pkt(size_t k);
    virtual bool getMulticast_pkt_in_CIDR_core() const;
    virtual void setMulticast_pkt_in_CIDR_core(bool multicast_pkt_in_CIDR_core);
    virtual const Packet * getOriginal_pkt() const;
    virtual Packet * getOriginal_pktForUpdate() { handleChange();return const_cast<Packet *>(const_cast<EthernetMacHeader*>(this)->getOriginal_pkt());}
    virtual void setOriginal_pkt(Packet * original_pkt);
    virtual bool getIs_drop_notif() const;
    virtual void setIs_drop_notif(bool is_drop_notif);
    virtual void setInput_ports_passedArraySize(size_t size);
    virtual size_t getInput_ports_passedArraySize() const;
    virtual unsigned int getInput_ports_passed(size_t k) const;
    virtual void setInput_ports_passed(size_t k, unsigned int input_ports_passed);
    virtual void insertInput_ports_passed(unsigned int input_ports_passed);
    virtual void insertInput_ports_passed(size_t k, unsigned int input_ports_passed);
    virtual void eraseInput_ports_passed(size_t k);
    virtual const char * getOriginal_pkt_name() const;
    virtual void setOriginal_pkt_name(const char * original_pkt_name);
    virtual omnetpp::simtime_t getRecovery_time() const;
    virtual void setRecovery_time(omnetpp::simtime_t recovery_time);
    virtual void setAffected_addressesArraySize(size_t size);
    virtual size_t getAffected_addressesArraySize() const;
    virtual const MacAddress& getAffected_addresses(size_t k) const;
    virtual MacAddress& getAffected_addressesForUpdate(size_t k) { handleChange();return const_cast<MacAddress&>(const_cast<EthernetMacHeader*>(this)->getAffected_addresses(k));}
    virtual void setAffected_addresses(size_t k, const MacAddress& affected_addresses);
    virtual void insertAffected_addresses(const MacAddress& affected_addresses);
    virtual void insertAffected_addresses(size_t k, const MacAddress& affected_addresses);
    virtual void eraseAffected_addresses(size_t k);
    virtual omnetpp::simtime_t getSwift_send_time() const;
    virtual void setSwift_send_time(omnetpp::simtime_t swift_send_time);
    virtual long getCidr_base_flow_id() const;
    virtual void setCidr_base_flow_id(long cidr_base_flow_id);
    virtual int getCidr_base_src_gpu_idx() const;
    virtual void setCidr_base_src_gpu_idx(int cidr_base_src_gpu_idx);
    virtual bool getIn_src_sharding() const;
    virtual void setIn_src_sharding(bool in_src_sharding);
    virtual bool getUsing_orca() const;
    virtual void setUsing_orca(bool using_orca);
    virtual bool getUsing_elmo() const;
    virtual void setUsing_elmo(bool using_elmo);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetMacHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetMacHeader& obj) {obj.parsimUnpack(b);}

// cplusplus {{
    inline bool isEth2Header(const EthernetMacHeader& hdr)  { return isEth2Type(hdr.getTypeOrLength()); }  // typeOrLength is type
    inline bool isIeee8023Header(const EthernetMacHeader& hdr)  { return isIeee8023Length(hdr.getTypeOrLength()); }  // typeOrLength is length
// }}

/**
 * Class generated from <tt>inet/linklayer/ethernet/EtherFrame.msg:184</tt> by nedtool.
 * <pre>
 * //
 * //
 * // Ethernet control frames used by the PAUSE protocol
 * //
 * class EthernetControlFrame extends FieldsChunk
 * {
 *     //    EthernetHeader.etherType = ETHERTYPE_FLOW_CONTROL;
 *     int opCode = -1;
 * }
 * </pre>
 */
class INET_API EthernetControlFrame : public ::inet::FieldsChunk
{
  protected:
    int opCode = -1;

  private:
    void copy(const EthernetControlFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EthernetControlFrame&);

  public:
    EthernetControlFrame();
    EthernetControlFrame(const EthernetControlFrame& other);
    virtual ~EthernetControlFrame();
    EthernetControlFrame& operator=(const EthernetControlFrame& other);
    virtual EthernetControlFrame *dup() const override {return new EthernetControlFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getOpCode() const;
    virtual void setOpCode(int opCode);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetControlFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetControlFrame& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/ethernet/EtherFrame.msg:193</tt> by nedtool.
 * <pre>
 * //
 * // Ethernet frame used by the PAUSE protocol
 * //
 * class EthernetPauseFrame extends EthernetControlFrame
 * {
 *     chunkLength = ETHER_PAUSE_COMMAND_BYTES;
 *     opCode = ETHERNET_CONTROL_PAUSE;
 *     int pauseTime; // in 512 bit-time units
 * }
 * </pre>
 */
class INET_API EthernetPauseFrame : public ::inet::EthernetControlFrame
{
  protected:
    int pauseTime = 0;

  private:
    void copy(const EthernetPauseFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EthernetPauseFrame&);

  public:
    EthernetPauseFrame();
    EthernetPauseFrame(const EthernetPauseFrame& other);
    virtual ~EthernetPauseFrame();
    EthernetPauseFrame& operator=(const EthernetPauseFrame& other);
    virtual EthernetPauseFrame *dup() const override {return new EthernetPauseFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPauseTime() const;
    virtual void setPauseTime(int pauseTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetPauseFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetPauseFrame& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/ethernet/EtherFrame.msg:200</tt> by nedtool.
 * <pre>
 * class EthernetPadding extends FieldsChunk
 * {
 * }
 * </pre>
 */
class INET_API EthernetPadding : public ::inet::FieldsChunk
{
  protected:

  private:
    void copy(const EthernetPadding& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EthernetPadding&);

  public:
    EthernetPadding();
    EthernetPadding(const EthernetPadding& other);
    virtual ~EthernetPadding();
    EthernetPadding& operator=(const EthernetPadding& other);
    virtual EthernetPadding *dup() const override {return new EthernetPadding(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetPadding& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetPadding& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/linklayer/ethernet/EtherFrame.msg:204</tt> by nedtool.
 * <pre>
 * class EthernetFcs extends FieldsChunk
 * {
 *     chunkLength = ETHER_FCS_BYTES;
 *     uint32_t fcs;
 *     FcsMode fcsMode = FCS_MODE_UNDEFINED;
 * }
 * </pre>
 */
class INET_API EthernetFcs : public ::inet::FieldsChunk
{
  protected:
    uint32_t fcs = 0;
    inet::FcsMode fcsMode = FCS_MODE_UNDEFINED;

  private:
    void copy(const EthernetFcs& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EthernetFcs&);

  public:
    EthernetFcs();
    EthernetFcs(const EthernetFcs& other);
    virtual ~EthernetFcs();
    EthernetFcs& operator=(const EthernetFcs& other);
    virtual EthernetFcs *dup() const override {return new EthernetFcs(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint32_t getFcs() const;
    virtual void setFcs(uint32_t fcs);
    virtual inet::FcsMode getFcsMode() const;
    virtual void setFcsMode(inet::FcsMode fcsMode);

    EthernetFcs(FcsMode _fcsMode) : EthernetFcs() { fcsMode = _fcsMode; }
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetFcs& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetFcs& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_ETHERFRAME_M_H

