sudo mkdir /mnt/data2/leaf\ spine
sudo mkdir /mnt/data2/leaf\ spine/results
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_ENDED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_ENDED_QUERY_ID
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED_QUERY_ID
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED_COLLECTIVE_TYPE
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED_COLLECTIVE_ALG
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED_ACTUAL_TIME
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/REQUEST_SENT
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/NO_JITTER_REQUEST_SENT
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/PACKET_RCVED_APP_LAYER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/OOO_SEG_NUM
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/UTILIZATION
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/NUM_RTO
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DUP_ACKS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DUP_ACKS_AFTER_FR
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DUP_ACKS_FAST_RECOVERY
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DUP_ACKS_FAST_RETRANSMISSION
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/GRO_DELAYED_SEGMENT_LENGTH
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/RTT
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/BYTES_REQUESTED_FROM_SERVER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/REPLY_LENGTH_ASKED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DROP_SENDER_NAMES
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DROP_RECEIVER_NAMES
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DROPS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_DROPS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DROPS_IS_BURSTY
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DROPS_SEQS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DROPS_RET_COUNTS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/DROPS_RET_TOTAL_PAYLOAD_LEN
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_IN_QUEUE_DROP_COUNTER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_IN_RELAY_DROP_COUNTER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/QUEUEING_TIME
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/QUEUEING_TIME_INCAST
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/QUEUEING_TIME_FLOW_SIZE
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/QUEUE_LENGTH
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/QUEUE_LENGTH_PKT_BYTES
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FB_PACKET_GENERATED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FB_PACKET_GENERATED_Req_ID
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FB_PACKET_DROPPED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FB_PACKET_DROPPED_PORT
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/PACKET_DROPPED_FORWARDING_DISABLED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FB_BOUNCING_PASSED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/BURSTY_PKT_RCVED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/SYN_SENT
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/SYN_SENT_IS_BURSTY
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FIN_ACK_RCV
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/RECORDS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FIGS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/CHUNKS_RCVD_LENGTH
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/CHUNKS_RCVD_TOTAL_LENGTH
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/V2_RCVD_SOONER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/V2_RCVD_CORRECTLY
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/V2_RCVD_LATER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/V2_QUEUEING_TIME
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/NUM_MARKING_TIMEOUTS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/NUM_ORDERING_TIMEOUTS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/IP_PACKET_SENT_COUNTER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/IP_DATA_PACKET_SENT_COUNTER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/archive
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/NUM_SEGMENT_RETRANSMISSION
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/NUM_PACKETS_MARKED_DCTCP
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/NUM_TCP_CONNECTIONS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/HOP_COUNT
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_RTT_SUMS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_RTT_RECORD_COUNTS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/PER_PACKET_FABRIC_DELAY_SUM
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/PER_PACKET_FABRIC_DELAY_COUNTS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/SENT_PKTS_SEQ_NUMS
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_ALL_QUEUEING_TIME
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_MICE_QUEUEING_TIME
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_GOODPUT_NUM_BITS_SENT_TO_APP
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_THROUGHPUT_BITS_SENT
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_THROUGHPUT_BITS_RCVD
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/PER_PORT_QUEUE_LEN_BYTES
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/SHARED_MEM_LEN_BYTES
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/PKT_RANK
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/EXTRA
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/BITS_RCVD_LENGTH
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_NUM_PER_QUERY
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/FLOW_PASSED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/PFC_STOP_GENERATED
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/AGG_POPPED_BYTES
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/POPPED_DATA_PKT_NUM
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_LAST_DATA_POPPED_TIME
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_TREE_COUNTER
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_DATA_PKT_SENT_NUM
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_DATA_PKT_RCVD_NUM
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/LIGHT_OOO_DATA_COUNT
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/CONTROLLER_DELAY
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/MAX_SIMULTANEOUS_TREES
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/AUTOCCL_CHOSEN_ALG
sudo mkdir /mnt/data2/leaf\ spine/Constant\ Network\ Load/AUTOCCL_CHOSEN_COLLECTIVE

sudo mkdir /mnt/data/leaf\ spine
sudo mkdir /mnt/data/leaf\ spine/results
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_ENDED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_ENDED_QUERY_ID
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED_QUERY_ID
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED_COLLECTIVE_TYPE
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED_COLLECTIVE_ALG
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_STARTED_ACTUAL_TIME
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/REQUEST_SENT
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/NO_JITTER_REQUEST_SENT
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/PACKET_RCVED_APP_LAYER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/OOO_SEG_NUM
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/UTILIZATION
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/NUM_RTO
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DUP_ACKS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DUP_ACKS_AFTER_FR
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DUP_ACKS_FAST_RECOVERY
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DUP_ACKS_FAST_RETRANSMISSION
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/GRO_DELAYED_SEGMENT_LENGTH
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/RTT
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/BYTES_REQUESTED_FROM_SERVER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/REPLY_LENGTH_ASKED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DROP_SENDER_NAMES
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DROP_RECEIVER_NAMES
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DROPS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_DROPS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DROPS_IS_BURSTY
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DROPS_SEQS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DROPS_RET_COUNTS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/DROPS_RET_TOTAL_PAYLOAD_LEN
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_IN_QUEUE_DROP_COUNTER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_IN_RELAY_DROP_COUNTER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/QUEUEING_TIME
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/QUEUEING_TIME_INCAST
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/QUEUEING_TIME_FLOW_SIZE
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/QUEUE_LENGTH
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/QUEUE_LENGTH_PKT_BYTES
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FB_PACKET_GENERATED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FB_PACKET_GENERATED_Req_ID
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FB_PACKET_DROPPED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FB_PACKET_DROPPED_PORT
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/PACKET_DROPPED_FORWARDING_DISABLED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FB_BOUNCING_PASSED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/BURSTY_PKT_RCVED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/SYN_SENT
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/SYN_SENT_IS_BURSTY
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FIN_ACK_RCV
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/RECORDS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FIGS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/CHUNKS_RCVD_LENGTH
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/CHUNKS_RCVD_TOTAL_LENGTH
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/V2_RCVD_SOONER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/V2_RCVD_CORRECTLY
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/V2_RCVD_LATER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/V2_QUEUEING_TIME
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/NUM_MARKING_TIMEOUTS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/NUM_ORDERING_TIMEOUTS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/IP_PACKET_SENT_COUNTER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/IP_DATA_PACKET_SENT_COUNTER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/archive
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/NUM_SEGMENT_RETRANSMISSION
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/NUM_PACKETS_MARKED_DCTCP
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/NUM_TCP_CONNECTIONS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/HOP_COUNT
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_RTT_SUMS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_RTT_RECORD_COUNTS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/PER_PACKET_FABRIC_DELAY_SUM
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/PER_PACKET_FABRIC_DELAY_COUNTS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/SENT_PKTS_SEQ_NUMS
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_ALL_QUEUEING_TIME
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_MICE_QUEUEING_TIME
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_GOODPUT_NUM_BITS_SENT_TO_APP
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_THROUGHPUT_BITS_SENT
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_THROUGHPUT_BITS_RCVD
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/PER_PORT_QUEUE_LEN_BYTES
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/SHARED_MEM_LEN_BYTES
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/PKT_RANK
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/EXTRA
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/BITS_RCVD_LENGTH
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_NUM_PER_QUERY
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/FLOW_PASSED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/PFC_STOP_GENERATED
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/AGG_POPPED_BYTES
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/POPPED_DATA_PKT_NUM
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_LAST_DATA_POPPED_TIME
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_TREE_COUNTER
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_DATA_PKT_SENT_NUM
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_DATA_PKT_RCVD_NUM
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/LIGHT_OOO_DATA_COUNT
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/CONTROLLER_DELAY
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/MAX_SIMULTANEOUS_TREES
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/AUTOCCL_CHOSEN_ALG
sudo mkdir /mnt/data/leaf\ spine/Constant\ Network\ Load/AUTOCCL_CHOSEN_COLLECTIVE


sudo chown -R sepehr /mnt/data2/leaf\ spine/
sudo chown -R sepehr /mnt/data/leaf\ spine/

